spring:
  output:
    ansi:
      enabled: always

  # Development Server PostgreSQL
  datasource:
    url: jdbc:postgresql://144.24.90.88:5432/planit
    username: planit
    password: planit
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Development Server Redis
  data:
    redis:
      host: 144.24.90.88
      port: 6379
      password: planit
      repositories:
        enabled: false

logging:
  level:
    com.planit: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    web: debug
